---
title: 'R-intro: course contents'
author: "João Gonçalves"
date: "7 de Julho de 2018"
output:
  html_document: default
  pdf_document:
    toc: true
    toc_depth: 4
    fig_height: 0.5
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Overview


In this introductory course to R you will learn how to master the basics of this beautiful and immensely useful open-source language. R currently has a growing number of users and its applications in both academia and in the private sector are also increasing in a yearly basis.  

The course will provide an introduction to the fundamental elements of R, starting from basic data structures and functions up to more complex stuff such as `if` conditionals and `for` loops. With the knowledge acquired from this course, you will be ready to undertake your own data analysis and be capable of pursuing more advanced topics. 

Our exploration will start by focusing on some key aspects of R as programming language, its syntax and slowly introduce some of the functions used for basic statistics such as those used for summarizing data (e.g., mean, standard-deviation), pairwise correlation and linear models.


# Pre-requisites


Don't worry we will start slowly! :-) As such, you don't really need any prior knowledge of computer programming (although some previous experience will make things easier) however, some familiarity with basic mathematical and statistical concepts and notions is assumed (e.g., distributions, centrality and dispersion measures, quantiles). 


# Course content by session


## Session 1


 - Exploring RStudio environment and workflow
 
 - Understanding the very basics of Rmarkdown
 
 - Starting a work session
 
 - Using the help system
 
 - R as a (sophisticated) calculator
 
 - Vectors and matrices: understanding the differences
 
 - Indexation by position, name or using logical conditions 
 

## Session 2


 - Time for recap session #1

 - Factors
 
 - Lists

 - Functions 
 
 - If conditionals 
 
 - For loops 
 
 - Combining all together

 - Working with dataframes
 
 - Data import/export in different formats
 

## Session 3


 - Time for recap session #2

 - Linear models in R: intro notes

 - Checking model assumptions
 
 - Building linear models in R
 
 - Checking model fit and interpreting results
 
 - Model cross-validation (time to practice `for` loops)


## Session 4?

 - An intro to the tidyverse:
 
    - Summarizing data with dplyr
    
    - Making pretty plots in ggplot2     
    
 - Other topics in R-intro??
